apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels: 
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:4.0.11
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  type: ClusterIP
  selector:
    app: cassandra
  ports:
  - name: cassandra
    port: 9042
    targetPort: 9042
