apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-populate
  labels:
    app: cassandra-populate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: cassandra-populate
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
