version: "3.7"
services:
  
  # (first compile jar and put in jar folder)
  spark-submit:
    image: bitnami/spark:3.3.4
    container_name: spark-submit
    command: /submit_spark_job.sh
    env_file: 
      - ./.env
    volumes:
      - ./jars:/jars
      - ./submit_spark_job.sh:/submit_spark_job.sh
      - ./../models:/models
    networks:
      - fbid


networks:
  fbid:
